# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - Frontend/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core'
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: CmdLine@2
  displayName: 'Install dotnet ef'
  inputs:
    script: 'dotnet tool update --global dotnet-ef'

- task: DotNetCoreCLI@2
  displayName: 'Restore WebAPI'
  inputs:
    command: 'restore'
    projects: '**/eCommerce.WebAPI.csproj'
    feedsToUse: 'select'

- task: CmdLine@2
  displayName: 'EF Migrations Script'
  inputs:
    script: 'dotnet ef migrations script --project eCommerce.Persistence\eCommerce.Persistence.csproj --startup-project eCommerce.Persistence\eCommerce.Persistence.csproj -i -o $(build.artifactstagingdirectory)\API_DbMigrations.sql'

- task: DotNetCoreCLI@2
  displayName: 'Publish eCommerce.WebAPI'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/eCommerce.WebAPI.csproj'
    arguments: '--configuration release --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'