# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - Frontend/eCommerce.WebAdmin

pool:
  vmImage: 'windows-latest'

variables:
  configuration: release
  project: '**/eCommerce.WebAdmin.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core'
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore .NET'
  inputs:
    command: 'restore'
    projects: $(project)
    feedsToUse: 'select'

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '12.x'
    checkLatest: true

- task: Npm@1
  displayName: 'Install Angular CLI'
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli@latest'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(project)
    arguments: '--configuration $(configuration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'eCommerce-webadmin'
    publishLocation: 'Container'